### ISSUE TITLE
How to and two query with like?

### ISSUE THREAD

**Issue by yepco** [williamoliveira/eloquent-array-query-builder#1]
I have url like this
`?where[title][like]=%ww%&where[id]=2&fields[]=id`
return 
`[{"id":2},{"id":3},{"id":4}]`
My question is I have two condition but execute first.
When I change it this:
`?where[id]=2&where[title][like]=%ww%&fields[]=id`
return 
`[{"id":2}]`

**Comment by williamoliveira** [comment]
Hi, thank you for your interest

I don't think I got your question right, it is not returning the expected result?
If so, could you examplefy the desired result and what it is giving?
