### ISSUE TITLE
Installation failed, reverting ./composer.json to its original content

### ISSUE THREAD

**Issue by ckshameer** [williamoliveira/eloquent-array-query-builder#19]
Installation failed,

williamoliveira/eloquent-array-query-builder v1.1.0 requires illuminate/database <=5.3 -> satisfiable by illuminate/database[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 5.0.x-dev, 5.1.x-dev, 5.2.x-dev, v1.0.0, v1.1.0, v1.1.1, v4.0.0, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0-BETA1, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.27, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0].
    - Can only install one of: illuminate/database[v1.0.0, v5.7.20].
    - Can only install one of: illuminate/database[v1.1.0, v5.7.20].
    - Can only install one of: illuminate/database[v1.1.1, v5.7.20].
    - Installation request for illuminate/database (locked at v5.7.20) -> satisfiable by illuminate/database[v5.7.20].

**Comment by williamoliveira** [comment]
Could you try v1.4.1-alpha or dev-master? I bumped Laravel to 5.7

**Comment by vhs1092** [comment]
I tried with
"williamoliveira/eloquent-array-query-builder": "^1.4.1-alpha",

and throws 
The requested package williamoliveira/eloquent-array-query-builder ^1.4.1-alpha exists as williamoliveira/eloquent-array-query-builder[dev-develop, dev-master, v1.0-alpha, v1.0-alpha.1, v1.0-alpha.2, v1.0.0, v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.2.0, v1.3.0, v1.3.1, v1.4.0] but these are rejected by your constraint.

and with 
"williamoliveira/eloquent-array-query-builder": "dev-master",

Installation request for williamoliveira/eloquent-array-query-builder dev-master -> satisfiable by williamoliveira/eloquent-array-query-builder[dev-master].
    - Conclusion: don't install laravel/framework v5.7.2
    - Conclusion: don't install laravel/framework v5.7.1
    - williamoliveira/eloquent-array-query-builder dev-master requires illuminate/database 5.0.*|5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.* -> satisfiable by illuminate/database

**Comment by williamoliveira** [comment]
@vhs1092 could you try again please? It wasnt updated on Packagist for some reason

**Comment by vhs1092** [comment]
thank you it is working now.!
