### ISSUE TITLE
how to send query as JSON instead of query string

### ISSUE THREAD

**Issue by essivision** [williamoliveira/eloquent-array-query-builder#2]
Hi

Thanks for your package. I want to send query param with JSON format instead of query string. What should I do?

Thanks

**Comment by williamoliveira** [comment]
You could do something like this:

send a GET to `"/your-endpoint?query=" + encodeURIComponent(JSON.stringify(yourQueryObject))`
then on backend:
```
$router->get('/your-endpoint', function (\Illuminate\Http\Request $request, \Williamoliveira\ArrayQueryBuilder\ArrayBuilder $arrayBuilder) {
    $yourQueryObject = json_decode($request->get('query'));

    $query = User::query();
    $query = $arrayBuilder->apply($query, $yourQueryObject);

    return $query->paginate($request->get('per_page'));
});
```

another approach, the one I do, is to convert the query object to query string using https://github.com/ljharb/qs

**Comment by essivision** [comment]
Thanks for your answer but when I define a object in JavaScript, I had to define just one `where` property and doesn't define multiple `where` property. How to handle like this:
```
query = {
            where:{
                created_at:{
                    between:['2014-10-10','2015-10-10']
                }
            },
            where:{
                name:{
                    like:'%joao%'
                }
            }
        }
```
and error me in my editor duplicate declaration.

**Comment by williamoliveira** [comment]
Hi,
Just put all where conditions in the same object

```
query = {
            where:{
                created_at:{
                    between:['2014-10-10','2015-10-10']
                },
                name:{
                    like:'%joao%'
                }
            }
        }
```
