### ISSUE TITLE
Support Laravel 6.0 and 7.0

### ISSUE THREAD

**Issue by avambro** [williamoliveira/eloquent-array-query-builder#22]
Hi, 

Could you be gentle to help me add support for Laravel 6.x or 7.x?

Thank you

**Comment by williamoliveira** [comment]
If nothing changed its just a matter of putting the new versions here: https://github.com/williamoliveira/eloquent-array-query-builder/blob/master/composer.json#L12
I do not work with Laravel anymore but you can make a commit and submit a PR if you want

**Comment by williamoliveira** [comment]
Fixed: https://github.com/williamoliveira/eloquent-array-query-builder/pull/23
