### ISSUE TITLE
groupBy in array query builder

### ISSUE THREAD

**Issue by essivision** [williamoliveira/eloquent-array-query-builder#4]
Hi

How to groupBy in your library like this?

```
$users = User::orderBy('name', 'desc')
                ->groupBy('count')
                ->having('count', '>', 100)
                ->get();
```

**Comment by williamoliveira** [comment]
Hi, it does not have this feature yet, I will implement it soon

**Comment by essivision** [comment]
It's very good

**Comment by paranoid-m** [comment]
Hi
I add this item
Add this in apply function 
` if (isset($arrayQuery['groupby'])) {
            $this->buildgroupBy($query, $arrayQuery['groupby']);
        }`
And add this function in ArrayBuilder file
`    public function buildgroupBy($queryBuilder, $columns)
    {
        $queryBuilder->groupBy($columns);
    }`
use this
`&groupby=cat_id`
Good luck
