### ISSUE TITLE
Is it possible to add SUM, MAX, MIN, AVG, COUNT to query builder

### ISSUE THREAD

**Issue by essivision** [williamoliveira/eloquent-array-query-builder#5]
Hi William,

Is it possible to add SUM, MAX, MIN, AVG, COUNT to number fields in query builder? I think it's essential to real world project and it useful to get complete report from eloquent.

Thanks

**Comment by williamoliveira** [comment]
I am in a busy moment right now, I don't know when I will have time to improve this package

**Comment by essivision** [comment]
Is possible to help me to add this feature to your library by myself?

**Comment by paranoid-m** [comment]
Hi,
I add this in apply function 
`    public function buildmax($queryBuilder, $columns)
    {
             $queryBuilder->max($columns);
    }`
and add this function in ArrayBuilder.php 
`   public function buildmax($queryBuilder, $columns)
    {
             $queryBuilder->max($columns);
    }`
and use `&max=id` but it dose not work. 
Can you help me?

**Comment by williamoliveira** [comment]
The thing with this kind of function and also why the reason its not working for you, is that it executes the query and returns the results

I am not sure if we should add functions that executes the query to this package, the original idea of it was to just add filters to a query, not to be a full featured query builder

**Comment by paranoid-m** [comment]
Ok that's right 
But how to add max,min,avg to your package?
If you have not enough time ,What's your adea?
Thanks alot

**Comment by williamoliveira** [comment]
What about placing this kind of function (that executes the query) on a separated class?
