### ISSUE TITLE
Support Laravel 5.3

### ISSUE THREAD

**Issue by paranoid-m** [williamoliveira/eloquent-array-query-builder#6]
Hi ,
When you release for laravel 5.3?

**Comment by williamoliveira** [comment]
Done [v1.1.0](https://github.com/williamoliveira/eloquent-array-query-builder/releases/tag/v1.1.0)

**Comment by paranoid-m** [comment]
Thanks but when I run this commsnds on laravel 5.3
 `composer require williamoliveira/eloquent-array-query-builder`
show me this errors

>   Problem 1
    - Conclusion: remove laravel/framework v5.3.26
    - Conclusion: don't install laravel/framework v5.3.26
    - williamoliveira/eloquent-array-query-builder v1.1.0 requires illuminate/database <=5.3 -> satisfiable by laravel/framework[v5.3.0],

**Comment by williamoliveira** [comment]
Thank you for your reply.
I had put the Laravel version requirement wrong, sorry, but I think it's fixed now, could you please try again?

**Comment by paranoid-m** [comment]
Thanks a lot. It's work correctly.
